<?php

$definitions = [
    'navigation_cache' => [
        'mode' => cache_store::MODE_REQUEST,
        'requiredkeys' => false,
        'simplekeys' => true,
        'requirelockingwrite' => false,
        'simpledata' => false,
        'ttl' => 0,
    ],
    'image_cache' => [
        'mode' => cache_store::MODE_APPLICATION,
        'simplekeys' => true,
        'simpledata' => false,
        'requireidentifiers' => [],
        'requirelockingread' => false,
        'requirelockingwrite' => true,
        'requirelockingbeforewrite' => false,
        'maxsize' => null,
        'overrideclass' => null,
        'overrideclassfile' => null,
        'datasource' => null,
        'datasourcefile' => null,
        'staticacceleration' => false,
        'staticaccelerationsize' => null,
        'ttl' => 300,
        'mappingsonly' => false,
        'invalidationevents' => [],
        'canuselocalstore' => false,
        'sharingoptions' => cache_definition::SHARING_DEFAULT,
        'defaultsharing' => cache_definition::SHARING_DEFAULT,
    ],
    'main_page_cache' => [
        'mode' => cache_store::MODE_APPLICATION,
        'simplekeys' => true,
        'simpledata' => false,
        'requireidentifiers' => [],
        'requirelockingread' => false,
        'requirelockingwrite' => true,
        'requirelockingbeforewrite' => false,
        'maxsize' => null,
        'overrideclass' => null,
        'overrideclassfile' => null,
        'datasource' => null,
        'datasourcefile' => null,
        'staticacceleration' => false,
        'staticaccelerationsize' => null,
        'ttl' => 300,
        'mappingsonly' => false,
        'invalidationevents' => [],
        'canuselocalstore' => false,
        'sharingoptions' => cache_definition::SHARING_DEFAULT,
        'defaultsharing' => cache_definition::SHARING_DEFAULT,
    ],
];